# Generated by Django 2.2.3 on 2019-07-31 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketindex',
            options={'verbose_name_plural': 'market_indices'},
        ),
    ]
