# Generated by Django 2.2.3 on 2019-08-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0002_auto_20190731_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueupdate',
            name='market_status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
