# Generated by Django 2.2.3 on 2019-10-08 09:08

import json
import logging
import os

from django.conf import settings
from django.db import IntegrityError, migrations


def load_from_json_file():
    """Helper function to load data from JSON file."""
    data = []
    try:
        fpath = os.path.join(settings.BASE_DIR, 'tickers.json')
        with open(fpath, 'r') as fp:
            data = json.load(fp)
    except Exception as e:
        logging.warning(f'Error opening tickers file: {e}')
    return data


def initialize_market_index_table(apps, schema_editor):
    """Populates MarketIndex table with main indices."""
    MarketIndex = apps.get_model('main_board.MarketIndex')
    indices = load_from_json_file()
    if indices:
        for ind in indices:
            try:
                MarketIndex.objects.create(**ind)
            except IntegrityError:
                logging.warning(
                    f"Ticker symbol {ind['ticker']} already exists."
                )


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0003_valueupdate_market_status'),
    ]

    operations = [
        migrations.RunPython(initialize_market_index_table),
    ]
